import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import Layout from "@/components/Layout";
import { 
  FileText, 
  CheckCircle, 
  XCircle, 
  Share2, 
  Download, 
  Award,
  Clock,
  Shield,
  Eye,
  Search
} from 'lucide-react';

const CaseSummary = () => {
  const [trustCheckFindings, setTrustCheckFindings] = useState('');
  const [visualCheckFindings, setVisualCheckFindings] = useState('');
  const [keyEvidence, setKeyEvidence] = useState('');
  const [reasoning, setReasoning] = useState('');
  const [selfAssessment, setSelfAssessment] = useState<string[]>([]);

  const selfAssessmentChecklist = [
    'I completed the Trust Check thoroughly',
    'I completed the Visual Check thoroughly',
    'I have enough evidence to decide',
    'I can explain my reasoning to my team'
  ];

  const toggleAssessment = (item: string) => {
    setSelfAssessment(prev => 
      prev.includes(item) 
        ? prev.filter(i => i !== item)
        : [...prev, item]
    );
  };

  const formatReport = () => {
    const report = `
FACT-CHECK INVESTIGATION REPORT
==============================

TRUST CHECK FINDINGS:
${trustCheckFindings || 'No findings documented yet'}

VISUAL CHECK FINDINGS:
${visualCheckFindings || 'No findings documented yet'}

KEY EVIDENCE:
${keyEvidence || 'No evidence documented yet'}

REASONING & CONCLUSION:
${reasoning || 'No reasoning documented yet'}

INVESTIGATION CHECKLIST:
${selfAssessmentChecklist.map(item => 
  selfAssessment.includes(item) ? '✓ ' + item : '☐ ' + item
).join('\n')}

GENERATED BY: Fact-Check Detective Toolkit
TIMESTAMP: ${new Date().toLocaleString()}
    `;
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fact-check-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };


  const completionPercentage = Math.round((selfAssessment.length / selfAssessmentChecklist.length) * 100);

  return (
    <Layout title="Make Your Final Decision" showBackButton>
      {/* Header */}
      <Card className="detective-card mb-8">
        <CardHeader>
          <CardTitle className="flex items-center justify-between">
            <span className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              Make Your Final Decision
            </span>
            <span className="text-sm text-muted-foreground">
              Self-Assessment: {completionPercentage}%
            </span>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground text-center">
            Document your investigation findings and make your own decision based on the evidence you've gathered.
          </p>
        </CardContent>
      </Card>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* Manual Documentation Workspace */}
        <Card className="detective-card lg:col-span-2">
          <CardHeader>
            <CardTitle>Document Your Investigation</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="text-sm font-medium">Summarize your findings from the Trust Check:</label>
                <Textarea
                  placeholder="What did you discover about the sources? What trusted sites covered it? What red flags did you find?"
                  value={trustCheckFindings}
                  onChange={(e) => setTrustCheckFindings(e.target.value)}
                  className="min-h-32"
                />
              </div>
              
              <div className="space-y-2">
                <label className="text-sm font-medium">Summarize your findings from the Visual Check:</label>
                <Textarea
                  placeholder="What did reverse image searches reveal? Did you find signs of manipulation? What about video authenticity?"
                  value={visualCheckFindings}
                  onChange={(e) => setVisualCheckFindings(e.target.value)}
                  className="min-h-32"
                />
              </div>
            </div>
            
            <div className="space-y-2">
              <label className="text-sm font-medium">List your key evidence:</label>
              <Textarea
                placeholder="What are the most important pieces of evidence that support your conclusion?"
                value={keyEvidence}
                onChange={(e) => setKeyEvidence(e.target.value)}
                className="min-h-24"
              />
            </div>
            
            <div className="space-y-2">
              <label className="text-sm font-medium">Explain your reasoning and final decision:</label>
              <Textarea
                placeholder="Based on all your investigation, what do you conclude? Is it true, false, or unclear? Why?"
                value={reasoning}
                onChange={(e) => setReasoning(e.target.value)}
                className="min-h-32"
              />
            </div>
          </CardContent>
        </Card>

        {/* Self-Assessment Checklist */}
        <Card className="detective-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <CheckCircle className="h-5 w-5 text-success" />
              Investigation Self-Assessment
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {selfAssessmentChecklist.map((item, index) => (
              <div
                key={index}
                className="flex items-start space-x-3 p-3 rounded-lg hover:bg-muted/50 transition-colors"
              >
                <Checkbox
                  id={`assessment-${index}`}
                  checked={selfAssessment.includes(item)}
                  onCheckedChange={() => toggleAssessment(item)}
                />
                <label
                  htmlFor={`assessment-${index}`}
                  className={`text-sm cursor-pointer ${
                    selfAssessment.includes(item) ? 'text-success font-medium' : ''
                  }`}
                >
                  {item}
                </label>
              </div>
            ))}
            
            {/* Progress Bar */}
            <div className="w-full bg-muted rounded-full h-2 mt-4">
              <div 
                className="h-2 rounded-full teal-gradient transition-all duration-500"
                style={{ width: `${completionPercentage}%` }}
              />
            </div>
          </CardContent>
        </Card>

        {/* Format Report Option */}
        <Card className="detective-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              Report Formatting
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Once you've documented your findings above, you can format them into a clean report.
            </p>
            
            <Button 
              onClick={formatReport}
              className="w-full"
              disabled={!trustCheckFindings && !visualCheckFindings && !keyEvidence && !reasoning}
            >
              <Download className="h-4 w-4 mr-2" />
              Format My Report
            </Button>
            
            <div className="text-center p-4 bg-muted/30 rounded-lg">
              <p className="text-xs text-muted-foreground">
                This formats YOUR written content into a professional report - it doesn't generate content for you.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Final Action */}
      <Card className="detective-card mt-8">
        <CardContent className="text-center py-8">
          <h2 className="text-2xl font-bold text-foreground mb-4">
            Ready to Present Your Investigation? 🎉
          </h2>
          <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
            You've documented your findings using professional investigation methods. 
            Your conclusions are based on your own analysis of the evidence.
          </p>
          <div className="flex gap-4 justify-center">
            <Button size="lg" variant="outline" asChild>
              <Link to="/">
                Start New Investigation
              </Link>
            </Button>
            <Button size="lg" className="glow-gold" asChild>
              <Link to="/trust-check">
                Practice Another Case
              </Link>
            </Button>
          </div>
        </CardContent>
      </Card>
    </Layout>
  );
};

export default CaseSummary;